---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-dev
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev  
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io